FROM archlinux:latest

RUN pacman -Syu --noconfirm && pacman -S --noconfirm \
    base-devel \
    cmake \
    qt6-base \
    qt6-declarative \
    polkit-qt6 \
    sqlite \
    pacman-contrib \
    git \
    && pacman -Scc --noconfirm

WORKDIR /app
