FROM fedora:44
RUN dnf5 -y --setopt=install_weak_deps=False install \
    gcc-c++ cmake qt6-qtbase-devel qt6-qtdeclarative-devel qt6-qtsvg-devel \
    polkit-qt6-1-devel sqlite-devel pkgconf-pkg-config desktop-file-utils appstream kf6-kirigami \
    && dnf5 clean all
WORKDIR /app
ENV QT_QPA_PLATFORM=offscreen QT_FORCE_STDERR_LOGGING=1 LANG=C.UTF-8
